INSERT INTO players (name) VALUES ('Roger Federer');
INSERT INTO players (name) VALUES ('Rafael Nadal');
INSERT INTO players (name) VALUES ('Novak Djokovic');
INSERT INTO players (name) VALUES ('Jannik Sinner');
INSERT INTO players (name) VALUES ('Carlos Alcaraz');
INSERT INTO players (name) VALUES ('Casper Ruud');
INSERT INTO players (name) VALUES ('Grigor Dimitrov');
INSERT INTO players (name) VALUES ('Marcos Giron');
INSERT INTO players (name) VALUES ('Flavio Cobolli');
INSERT INTO players (name) VALUES ('Alex De Minaur');
INSERT INTO players (name) VALUES ('Stefanos Tsitsipas');
INSERT INTO players (name) VALUES ('Hubert Hurkacz');
INSERT INTO players (name) VALUES ('Taylor Fritz');
INSERT INTO players (name) VALUES ('Даниил Медведев');
INSERT INTO players (name) VALUES ('Tommy Paul');
INSERT INTO players (name) VALUES ('Alexander Zverev');
INSERT INTO players (name) VALUES ('Ben Shelton');
INSERT INTO players (name) VALUES ('Александр Бублик');
INSERT INTO players (name) VALUES ('Jiri Lehecka');
INSERT INTO players (name) VALUES ('Jack Draper');
INSERT INTO players (name) VALUES ('Tallon Griekspoor');
INSERT INTO players (name) VALUES ('Алексей Попырин');
INSERT INTO players (name) VALUES ('Laslo Djere');
INSERT INTO players (name) VALUES ('Miomir Kecmanovic');
INSERT INTO players (name) VALUES ('Daniel Evans');


INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 2, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 4, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 5, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 6, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 7, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 8, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 11, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 12, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 18, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 2, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 5, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 6, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 7, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 8, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 6, 6);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 9, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 10, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 17, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 18, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 3, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 4, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 9, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 10, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 11, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 6, 6);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 12, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 13, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 14, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (15, 10, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 15, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 16, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (6, 20, 6);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 17, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 18, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 3, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 9, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 10, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 17, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 14, 14);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 14, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 15, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 17, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 18, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 4, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 5, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 6, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (23, 10, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 7, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 10, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 11, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 12, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 6, 6);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 13, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 14, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (23, 2, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 15, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 16, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 5, 21);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 17, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 18, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 8, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 9, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 10, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 11, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (17, 10, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 12, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 13, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (18, 17, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 14, 14);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 15, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 14, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 15, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 16, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (23, 22, 23);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 17, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 18, 3);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 4, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 6, 6);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (2, 15, 2);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 9, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (22, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 10, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 18, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 12, 12);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 14, 14);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 3, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 16, 16);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 17, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (3, 18, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 5, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 6, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 5, 5);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 7, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 8, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 9, 4);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (23, 22, 22);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 7, 7);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 8, 8);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 9, 9);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 10, 10);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 11, 11);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (19, 12, 19);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 13, 13);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 13, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 16, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (21, 19, 19);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 17, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (25, 1, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (24, 25, 24);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 14, 14);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 15, 15);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 17, 17);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (4, 18, 18);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 9, 1);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (20, 21, 20);
INSERT INTO matches (player1_id, player2_id, winner_id) VALUES (1, 10, 1);
